apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-countdown
spec:
  template:
    metadata:
      name: test-job-countdown
    spec:
      containers:
      - name: counter
        image: alpine
        command:
         - "bin/sh"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never